# Generated by Django 3.2.9 on 2021-12-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='prompt_text',
        ),
        migrations.AddField(
            model_name='proposal',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='step',
            name='prompt',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='thought',
            name='thought_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
