# Generated by Django 3.2.9 on 2021-12-03 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20211203_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='proposal_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='stories.step'),
        ),
        migrations.AlterField(
            model_name='step',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='stories.story'),
        ),
        migrations.AlterField(
            model_name='thought',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thoughts', to='stories.proposal'),
        ),
    ]
