# Generated by Django 3.2.9 on 2021-12-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20211203_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='prompt',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
