# Generated by Django 3.2.9 on 2021-12-03 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_alter_step_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='accepted_proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_step', to='stories.proposal'),
        ),
    ]
