# Generated by Django 3.2.9 on 2021-12-04 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_step_accepted_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='accepted_proposal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_step', to='stories.proposal'),
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_text', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='stories.proposal')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
