# Generated by Django 3.2.9 on 2021-12-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_auto_20211204_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='accepted_context',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='step',
            name='generated_context',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
